name: check
on: push
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Update log
        run: ./scripts/write-log.sh

      - name: Commit changes
        run: |
          git config --global user.name 'Update bot'
          git config --global user.email 'no-reply@redbull.design'
          git commit -am 'Automated logs update'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
