name: check
on: push
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Update log
        run: ./scripts/write-log.sh

      - name: Commit changes
        run: |
          git config --global user.name 'Update bot'
          git config --global user.email 'no-reply@redbull.design'
          git add .
          git diff-index --quiet HEAD || git commit -m 'Automated logs update'
          git push -u origin HEAD

      - name: Push changes
        uses: actions/checkout@v2
