name: test
on: push
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: "Job 1: Do nothing"
        run: exit 0

  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: "Job 2: Do nothing"
        run: exit 0
