on:
  workflow_run:
    workflows: ["check"]
    branches: [main]
    types:
      - completed

jobs:
  commit_snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: Test workflow run
        run: |
          echo 'test run'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
